### ISSUE TITLE
Exception at startup MainFX

### ISSUE THREAD

**Issue by b3b00** [zimmeluk/Brackets#1]
When trying to run brackets I get the following exception (from master branch): 
My conf : WIN10 + intellij + jdk 1.8.0_144

> "C:\Program Files\Java\jdk1.8.0_144\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.3\lib\idea_rt.jar=60889:C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.3\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_144\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_144\jre\lib\rt.jar;C:\Users\olduh\dev\Brackets\out\production\Brackets" io.github.zimmeluk.MainFX
> Exception in Application start method
> java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
> 	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
> Caused by: java.lang.RuntimeException: Exception in Application start method
> 	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
> 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.NullPointerException: Location is required.
> 	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3207)
> 	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3175)
> 	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3148)
> 	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3124)
> 	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3104)
> 	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:3097)
> 	at io.github.zimmeluk.MainFX.start(MainFX.java:21)
> 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
> 	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
> 	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
> 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
> 	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
> 	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
> 	... 1 more
> Exception running application io.github.zimmeluk.MainFX
> 
> Process finished with exit code 1

**Comment by b3b00** [comment]
I solved it removing the src folder : I moved all the io directory at the root of the repo. It seems that intellij idea ultimate does not like this src level.
